const productos=[
    /*-----------------------------COMIDAS-----------------------*/
    { nombre: "Empanada", categoria: "Comida", imagen:"IMAGENES/EMPANADA.png", precio: 2800 },
    { nombre: "Papa Rellena", categoria: "Comida", imagen:"IMAGENES/PAPA RELLENA.png", precio: 3600},
    { nombre: "Areburguer", categoria: "Comida", imagen:"IMAGENES/AREBURGER.png", precio: 6300 },
    { nombre: "Hamburguesa", categoria: "Comida", imagen:"IMAGENES/HAMBURGUESA.png", precio: 7000 },
    { nombre: "Pizza", categoria: "Comida", imagen:"IMAGENES/PIZZA.png", precio: 4600 },
    { nombre: "Arepa de Queso", categoria: "Comida ", imagen:"IMAGENES/AREPA_QUESO.png", precio: 2700 },
    { nombre: "Sandwich", categoria: "Comida", imagen:"IMAGENES/SANDWICH.png", precio: 3500 },
    { nombre: "Pastel de Pollo", categoria: "Comida", imagen:"IMAGENES/PASTEL DE POLLO.png", precio: 3400 },
    { nombre: "Perros", categoria: "Comida", imagen:"IMAGENES/PERRO.png", precio: 5500 },
    { nombre: "Pastel de Yuca", categoria: "Comida", imagen:"IMAGENES/Pastel de Yuca.png", precio: 3500 },
    { nombre: "Churros", categoria: "Comida", imagen:"IMAGENES/CHURRO.png", precio: 2500 },
    { nombre: "Burritos", categoria: "Comida ", imagen:"IMAGENES/BURRITO.png", precio: 6200 },
    { nombre: "Arepa de Huevo", categoria: "Comida", imagen:"IMAGENES/AREPA DE HUEVO.png", precio: 3700 },
    { nombre: "Arepa de Jamon y Queso", categoria: "Comida", imagen:"IMAGENES/AREPA JAMÓN Y QUESO.png", precio: 2700 },
    { nombre: "Sandwich Tajado de Jamon y Queso", categoria: "Comida", imagen:"IMAGENES/SANDWICH JAMÓN Y QUESO.png", precio: 2000 },
    { nombre: "Sandwich de Pollo", categoria: "Comida", imagen:"IMAGENES/SANDWICH POLLO.png", precio: 6000 },
    { nombre: "Arepa Blanca", categoria: "Comida", imagen:"IMAGENES/AREPA_SIN_SAL.png", precio: 600},
    {nombre: "Changua", categoria: "Comida", imagen:"IMAGENES/CHANGUA.png", precio:7500 },
    { nombre: "Salchichon", categoria: "comida", imagen:"IMAGENES/Salchichon.png", precio: 300},
    { nombre: "Pan solo", categoria: "Comida", imagen:"IMAGENES/Pan.png", precio: 1200},
    { nombre: "Huevo Cocido", categoria: "Comida", imagen:"IMAGENES/Huevo Cocido.png", precio: 1400},
    { nombre: "Tamales", categoria: "Comida", imagen:"IMAGENES/Tamal.png", precio: 7600},
    { nombre: "Huevo Rancheros", categoria: "Comida", imagen:"IMAGENES/Huevos con Salchicha.png", precio: 5200},
    { nombre: "Huevos al Gusto", categoria: "Comida ", imagen:"IMAGENES/Huevos al Gusto.png", precio: 4700},
    { nombre: "Huevpos Pericos con Salchicha", categoria: "Comida", imagen:"IMAGENES/Huevos Pericos con Salchicha.png", precio: 5700},
    { nombre: "Adicion Salchicha Ranchera", categoria: "Comida", imagen:"IMAGENES/ADICION_SALCHICHA_RANCHERA.png", precio: 1.700},
    { nombre: "Lasaña", categoria: "Comida", imagen:"IMAGENES/LASAÑA_.png", precio:14000 },
    {nombre: "Pastel de Carne", categoria: "Comida", imagen:"IMAGENES/Pastel de Carne.png", precio:3000 },
    {nombre: "Tajada de Queso", categoria: "Comida", imagen:"IMAGENES/QUESO_TAJADO.png", precio: 600 },
    {nombre: "Salchichas ", categoria: "Comida", imagen:"IMAGENES/SALCHICHA.png", precio:4500 },
    /* -------------------- BEBIDAS-------------------------------*/
    { nombre: "Hit de vidrio 250", categoria: "Bebidas", imagen:"IMAGENES/HIT VIDRIO 250.png", precio: 2300,},
    { nombre: "Postobon Retornable 1.25", categoria: "Bebidas ", imagen:"IMAGENES/POSTOBÓN RETORNABLE 1.25.png", precio: 6000 },
    { nombre: "Amper", categoria: "Bebidas ", imagen:"IMAGENES/AMPER.png", precio: 3700 },
    { nombre: "Red Bull", categoria: "Bebidas ", imagen:"IMAGENES/REDBULL.png", precio: 8000 },
    { nombre: "Coca Cola 350ml de Vidrio", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA 350 VIDRIO.png", precio: 2700},
    { nombre: "Coca Cola 1.5ml ", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA 1.5.png", precio: 7000},
    { nombre: "Coca Cola 500ml ", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA 500 ML.png", precio: 3500 },
    { nombre: "Coca Cola Mini", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA MINI.png", precio: 2200 },
    { nombre: "Coca Cola Mini de vidrio", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA MINI VIDRIO.png", precio: 1800 },
    { nombre: "Natu Mini", categoria: "Bebidas ", imagen:"IMAGENES/NATU MINI.png", precio: 1000 },
    { nombre: "Natu 400ml", categoria: "Bebidas ", imagen:"IMAGENES/NATU 400 ML.png", precio: 3000 },
    { nombre: "Natu de Vidrio", categoria: "Bebidas ", imagen:"IMAGENES/NATU VIDRIO.png", precio: 2400 },
    { nombre: "Hit en caja", categoria: "Bebidas ", imagen:"IMAGENES/HIT CAJA.png", precio: 1800 },
    { nombre: "Hit 500 ml", categoria: "Bebidas ", imagen:"IMAGENES/HIT 500 ML.png", precio: 3200 },
    { nombre: "Aloe", categoria: "Bebidas ", imagen:"IMAGENES/ALOE.png", precio: 2700 },
    { nombre: "speed", categoria: "Bebidas ", imagen:"IMAGENES/SPEED.png", precio: 2000 },
    { nombre: "Bretaña", categoria: "Bebidas ", imagen:"IMAGENES/BRETAÑA.png", precio: 3000 },
    { nombre: "Squash", categoria: "Bebidas ", imagen:"IMAGENES/SQUASH.png", precio: 3000 },
    { nombre: "Agua de Litro", categoria: "Bebidas ", imagen:"IMAGENES/AGUA LITRO.png", precio: 2800 },
    { nombre: "Agua 300ml", categoria: "Bebidas ", imagen:"IMAGENES/AGUA_CRISTAL_PEQUEÑA.png", precio: 1000 },
    { nombre: "Agua con Gas pequeña", categoria: "Bebidas ", imagen:"IMAGENES/AGUA GAS PEQUEÑA.png", precio: 1000 },
    { nombre: "Aguas 600", categoria: "Bebidas ", imagen:"IMAGENES/AGUA 600 ML.png", precio: 22000 },
    { nombre: "Agua con Gas Grande", categoria: "Bebidas ", imagen:"IMAGENES/AGUA GAS GRANDE.png", precio: 2300 },
    { nombre: "Agua H2O pequeña", categoria: "Bebidas ", imagen:"IMAGENES/H2O PEQUEÑA.png", precio: 1700 },
    { nombre: "Agua H2O", categoria: "Bebidas ", imagen:"IMAGENES/H2O GRANDE.png", precio: 3200 },
    { nombre: "Mister Tea", categoria: "Bebidas ", imagen:"IMAGENES/MISTER TEA.png", precio: 3000 },
    { nombre: "Te Hatsu", categoria: "Bebidas ", imagen:"IMAGENES/TE HATSU.png", precio: 5200 },
    { nombre: "Gaseosa Postobon Vidrio", categoria: "Bebidas ", imagen:"IMAGENES/POSTOBÓN VIDRIO.png", precio: 1700 },
    { nombre: "Acua", categoria: "Bebidas ", imagen:"IMAGENES/ACQUA.png", precio: 1900 },
    { nombre: "Tuti-Fruti", categoria: "Bebidas ", imagen:"IMAGENES/TUTIFRUTI.png", precio: 1900 },
    { nombre: "Gatorade sin Azucar", categoria: "Bebidas ", imagen:"IMAGENES/GATORADE SIN AZÚCAR.png", precio: 4000},
    { nombre: "Gatorade", categoria: "Bebidas ", imagen:"IMAGENES/GATORADE.png", precio: 4000 },
    { nombre: "Gatorlyte", categoria: "Bebidas ", imagen:"IMAGENES/GATORLYTE.webp", precio: 4000},
    { nombre: "Vaso de Gaseosa", categoria: "Bebidas ", imagen:"IMAGENES/VASO GASEOSA.png", precio: 1000 },
    { nombre: "Electrolit", categoria: "Bebidas", imagen:"IMAGENES/Elecrolit.png", precio:8800 },
    { nombre: "Speed en Lata", categoria: "Bebidas", imagen:"IMAGENES/Espeed en Lata.png", precio:2500 },
    { nombre: "Gaseosa Familiar", categoria: "Bebidas", imagen:"IMAGENES/Gaseosa Familiar.png", precio:8800 },

    /*------------------------------COMBOS---------------------------*/
    { nombre: "Combo de Sandwich", categoria: "Combos ", imagen:"IMAGENES/Combo de Sandwich (1).png", precio: 4400},
    { nombre: "Combo Pastel de Pollo", categoria: "Combos ", imagen:"IMAGENES/PASTEL DE POLLO.png", precio: 4200},
    { nombre: "Combo Hamburguesa", categoria: "Combos ", imagen:"IMAGENES/Combo de Hamburguesa.png", precio: 7800},
    { nombre: "Combo Areburguer", categoria: "Combos ", imagen:"IMAGENES/Combo Areburguer.png", precio: 7000},
    { nombre: "Combo Perro", categoria: "Combos ", imagen:"IMAGENES/combo_perro-removebg-preview.png", precio: 6300},

    /*----------------------------------PAQUETES------------------------------ */
    { nombre: "Detodito", categoria: "Paquetes ", imagen:"IMAGENES/detodito.png", precio: 3200},
    { nombre: "Papas", categoria: "Paquetes ", imagen:"IMAGENES/papas.png", precio: 2600},
    { nombre: "Platanos", categoria: "Paquetes ", imagen:"IMAGENES/platanitos.png", precio: 2600},
    { nombre: "Doritos", categoria: "Paquetes ", imagen:"IMAGENES/doritos.png", precio: 2800},
    { nombre: "Chitos", categoria: "Paquetes ", imagen:"IMAGENES/cheetos.png", precio: 2200},
    { nombre: "Choclitos", categoria: "Paquetes ", imagen:"IMAGENES/choclito.png", precio: 2.200},
    { nombre: "Trocipollo Pequeño", categoria: "Paquetes ", imagen:"IMAGENES/trocipollo.png", precio: 1800},
    { nombre: "Trocipollos Grande", categoria: "Paquetes ", imagen:"IMAGENES/trocippollo grande.png", precio: 3000},
    { nombre: "Cheese tris", categoria: "Paquetes ", imagen:"IMAGENES/cheese tres.png", precio: 2200},
    { nombre: "Tostacos", categoria: "Paquetes ", imagen:"IMAGENES/tostacos.png", precio: 2200},
    { nombre: "Doritos Dinamita", categoria: "Paquetes ", imagen:"IMAGENES/doritos flamin.png", precio: 3300},
    { nombre: "Mani con sal", categoria: "Paquetes ", imagen:"IMAGENES/MANI_CON_SAL.png", precio: 2000},
    { nombre: "Mani con pasas", categoria: "Paquetes ", imagen:"IMAGENES/mani sal y pasa.png", precio: 2000},
    { nombre: "ManiMoto", categoria: "Paquetes ", imagen:"IMAGENES/mani moto.png", precio: 2000},
    { nombre: "Chokis Bolitas", categoria: "Paquetes ", imagen:"IMAGENES/CHOKIS_BOLITAS.png", precio: 2000},
    { nombre: "Gomitas paquete", categoria: "Paquetes ", imagen:"IMAGENES/gomitas.png", precio: 2700},
    { nombre: "Herpos", categoria: "Paquetes ", imagen:"IMAGENES/herpo.png", precio: 800},
    { nombre: "Chocoramo", categoria: "Paquetes ", imagen:"IMAGENES/cohocorramo.png", precio: 2800},
    { nombre: "Gala", categoria: "Paquetes ", imagen:"IMAGENES/gala.png", precio: 2500},
    { nombre: "Gansito", categoria: "Paquetes ", imagen:"IMAGENES/gansito.png", precio: 1900},
    { nombre: "Chocoramo Barrita", categoria: "Paquetes ", imagen:"IMAGENES/CHOCORRAMO_BARRITA.png", precio: 2000},
    { nombre: "Achiras", categoria: "Paquetes ", imagen:"IMAGENES/achira.png", precio: 4700},
    { nombre: "Galletas Cocosette", categoria: "Paquetes", imagen:"IMAGENES/GALLETAS_COCOSETTE.png", precio:2200 },
    { nombre: "Cheese tris Grandes", categoria: "Paquetes", imagen:"IMAGENES/CHEESE_TRIS_GRANDE.png", precio:4500 },
    /*-------------------------------HELADOS---------------------------------------------- */
    { nombre: "Bonice", categoria: "Helado ", imagen:"IMAGENES/bonice-removebg-preview.png", precio: 1600},
    { nombre: "Bocato", categoria: "Helado ", imagen:"IMAGENES/bocato-removebg-preview.png", precio: 7000},
    { nombre: "Chococono", categoria: "Helado ", imagen:"IMAGENES/chococono-removebg-preview.png", precio: 3500},
    { nombre: "Artesanales", categoria: "Helado ", imagen:"IMAGENES/helado_artesanal-removebg-preview.png", precio: 3600},
    { nombre: "Minions ", categoria: "Helado ", imagen:"IMAGENES/paleta_minions-removebg-preview.png", precio: 2500},
    { nombre: "Aloha Mix", categoria: "Helado ", imagen:"IMAGENES/aloha-removebg-preview.png", precio: 3200},
    { nombre: "Aloha Agua", categoria: "Helado ", imagen:"IMAGENES/aloha_agua-removebg-preview.png", precio: 2500},
    { nombre: "Caseros", categoria: "Helado ", imagen:"IMAGENES/helado_casero-removebg-preview.png", precio: 2900},
    { nombre: "Chocolisto", categoria: "Helado ", imagen:"IMAGENES/helado_chocolisto-removebg-preview.png", precio: 2400},
    { nombre: "Platillo", categoria: "Helado ", imagen:"IMAGENES/platillo-removebg-preview.png", precio: 3700},
    { nombre: "Chococono Bakano", categoria: "Helado ", imagen:"IMAGENES/chococono-bakano-removebg-preview.png", precio: 3900},
    { nombre: "Polet grande", categoria: "Helado ", imagen:"IMAGENES/polet-removebg-preview.png", precio: 6500},
    { nombre: "Paleta Jet", categoria: "Helado ", imagen:"IMAGENES/paleta_jet-removebg-preview.png", precio: 5000},
    { nombre: "Compota", categoria: "Helado ", imagen:"IMAGENES/compota.png", precio: 3000},
    /*--------------------------------GRECA------------------------------------------------- */
    {nombre: "Tinto Pequeño", categoria: "Greca ", imagen:"IMAGENES/TINTO_PEQUEÑO.png", precio: 1100},
    {nombre: "Tinto Grande", categoria: "Greca ", imagen:"IMAGENES/TINTO_GRANDE.png", precio: 1800},
    {nombre: "Agua de Panela", categoria: "Greca", imagen:"IMAGENES/Agua de Panela.png", precio: 1900},
    {nombre: "Aromatica", categoria: "Greca", imagen:"IMAGENES/Aromatica.png", precio: 1.100},
    {nombre: "Aromatica Grande ", categoria: "Greca", imagen:"IMAGENES/Aromatica Grande.png", precio: 1800},
    {nombre: "Chocolate ", categoria: "Greca", imagen:"IMAGENES/Chocolate.png", precio: 2700},
    {nombre: "Milo pequeño", categoria: "Greca", imagen:"IMAGENES/MILO_PEQUEÑO.png", precio: 3100},
    {nombre: "Milo Grande ", categoria: "Greca", imagen:"IMAGENES/MILO_GRANDE.png", precio: 4600},
    {nombre: "Milo Deslactosado ", categoria: "Greca", imagen:"IMAGENES/Milo Deslactosado.png", precio: 3900},
    {nombre: "Perico", categoria: "Greca", imagen:"IMAGENES/PERICO_PEQUEÑO.png", precio: 1400},
    {nombre: "Cafe", categoria: "Greca", imagen:"IMAGENES/PERICO_GRANDE.png", precio: 2100},
    {nombre: "Cafe Deslactosado", categoria: "Greca", imagen:"IMAGENES/Cafe Deslactosado.png", precio: 2600,},
    {nombre: "Te chai en Agua", categoria: "Greca", imagen:"IMAGENES/TE_CHAI_AGUA.png", precio: 2900},
    {nombre: "Te chai en Leche ", categoria: "Greca", imagen:"IMAGENES/TE_CHAI_LECHE.png", precio: 2900},
    {nombre: "Vaso con Leche", categoria: "Greca", imagen:"IMAGENES/Vaso con Leche.png", precio: 2600},
    {nombre: "Arroz con Leche", categoria: "Greca", imagen:"IMAGENES/Arroz de Leche.png", precio: 3300},
    /*------------------------------------JUGOS Y FRUTERIA------------------------------------------- */
    {nombre: "Jugos en Leche", categoria: "Jugos y Fruteria", imagen:"IMAGENES/JUGOS_LECHE.png", precio:4600 },
    {nombre: "Batido Verde ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Batido Verde.png", precio:4.00 },
    {nombre: "Jugo en Agua", categoria: "Jugos y Fruteria", imagen:"IMAGENES/jugo en agua.png", precio:3200 },
    {nombre: "Gelatina ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Gelatina.png", precio:3000 },
    {nombre: "Yogurt con Granola", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Yogurt con Granola.png", precio:5200 },
    {nombre: "Vaso de Yogurt 7onz ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Vaso de Yogurt.png", precio:3000},
    {nombre: "Porcion de Fruta ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Porcion de Fruta.png", precio:3000 },
    {nombre: "Bananos ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Bananos.png", precio:1.000 },
    {nombre: "Manzanas  ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Manzanas.png", precio: 2000 },
    {nombre: "Salpicon ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Salpicon.png", precio: 2000 },
    {nombre: "Aguacate ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Aguacate.png", precio: 3000 },

    /*-------------------------------------PASTELERIA---------------------------------------- */
    {nombre: "Galletas de Avena ", categoria: "Pasteleria", imagen:"IMAGENES/Galleta de Avena.png", precio:1800 },
    {nombre: "Galletas de Vainilla ", categoria: "Pasteleria", imagen:"IMAGENES/Galletas de Vainilla.png", precio:1000 },
    {nombre: "Galletas de Chocolate ", categoria: "Pasteleria", imagen:"IMAGENES/Galletas de Chocolate.png", precio:2.00 },
    {nombre: "Mantecada ", categoria: "Pasteleria", imagen:"IMAGENES/Mantecada.png", precio:3000 },
    {nombre: "Torta de Queso  ", categoria: "Pasteleria", imagen:"IMAGENES/Torta de Queso.png", precio:3000 },
    {nombre: "Torta de Naranja ", categoria: "Pasteleria", imagen:"IMAGENES/Torta de Naranja.png", precio:3000 },
    {nombre: "Torta de Chocolate ", categoria: "Pasteleria", imagen:"IMAGENES/TORTA_CHOCOLATE.png", precio:3000},
    {nombre: "Brownie", categoria: "Pasteleria", imagen:"IMAGENES/Brownie.png", precio:3800 },
    {nombre: "Torta de Ciruela ", categoria: "Pasteleria", imagen:"IMAGENES/TORTA_CIRUELA.png", precio:3800 },
    {nombre: "Milhojas ", categoria: "Pasteleria", imagen:"IMAGENES/Milhojas - Amapolas.png", precio:3500 },
    {nombre: "Amapola ", categoria: "Pasteleria", imagen:"", precio:3500},
    {nombre: "Cocadas", categoria: "Pasteleria", imagen:"IMAGENES/Cocadas.png", precio:800},
    {nombre: "Flauta ", categoria: "Pasteleria", imagen:"", precio:800},
    {nombre: "Hojaldres de Bocadillo", categoria: "Pasteleria", imagen:"IMAGENES/Hojaldras de Bocadillo.png", precio:2000 },
    {nombre: "Croisant", categoria: "Pasteleria", imagen:"IMAGENES/CROISSANT.png", precio:2500},
    /*------------------------------------PRODUCTOS ALPINA---------------------------------------------- */
    {nombre: "Bilack Bolsa", categoria: "Productos Alpina", imagen:"IMAGENES/Bilack Bolsa.png", precio:2500 },
    {nombre: "Yogurt Alpina Original ", categoria: "Productos Alpina", imagen:"IMAGENES/Yogurt Alpina Original.png", precio:3400 },
    {nombre: "Avena Alpina ", categoria: "Productos Alpina", imagen:"IMAGENES/Avena Alpina.png", precio:4.200},
    {nombre: "Yox", categoria: "Productos Alpina", imagen:"IMAGENES/Yox.png", precio:3200},
    {nombre: "Regeneris", categoria: "Productos Alpina", imagen:"IMAGENES/Regeneris.png", precio:3900},
    {nombre: "Finesse", categoria: "Productos Alpina", imagen:"IMAGENES/Finesse - Original Deslactosado.png", precio: 4000},
    {nombre: "Bonyurt", categoria: "Productos Alpina", imagen:"IMAGENES/Bonyurt.png", precio: 4900},
    {nombre: "Alpin en Caja ", categoria: "Productos Alpina", imagen:"IMAGENES/Alpin en Caja.png", precio:4000 },
    {nombre: "Yogurt Griego", categoria: "Productos Alpina", imagen:"IMAGENES/YOGURT_GRIEGO.png", precio:6000},
    {nombre: "Kumis", categoria: "Productos Alpina", imagen:"IMAGENES/Kumis.png", precio:3500},
    {nombre: "Yogo Yogo en Bolsa", categoria: "Productos Alpina", imagen:"IMAGENES/Yogo Yogo en Bolsa.png", precio:1900 },
    {nombre: "Arequipe Alpina", categoria: "Productos Alpina", imagen:"IMAGENES/Arequipe Alpina.png", precio: 2500},
    /*---------------------------------------------DULCERIA--------------------------------------------------- */
    {nombre: "Queso y Quesadilas", categoria: "Dulceria", imagen:"IMAGENES/queso_quesadillas.png", precio:3000 },
    {nombre: "Bocadillo Veleño", categoria: "Dulceria", imagen:"IMAGENES/bocadillo_veleño.png", precio:800 },
    {nombre: "Bobbalo", categoria: "Dulceria", imagen:"IMAGENES/bobbaloo.png", precio: 300},
    {nombre: "Bianchi", categoria: "Dulceria", imagen:"IMAGENES/bianchi.png", precio:300 },
    {nombre: "Revolcon", categoria: "Dulceria", imagen:"IMAGENES/revolcon.png", precio: 300},
    {nombre: "Barrilete", categoria: "Dulceria", imagen:"IMAGENES/barrilete.png", precio: 700},
    {nombre: "Frunas", categoria: "Dulceria", imagen:"IMAGENES/frunas.png", precio:700 },
    {nombre: "Bombombum", categoria: "Dulceria", imagen:"IMAGENES/bombom bum.png", precio: 800},
    {nombre: "Mamut", categoria: "Dulceria", imagen:"IMAGENES/mamut.png", precio: 800},
    {nombre: "Trident Unidad", categoria: "Dulceria", imagen:"IMAGENES/trident 1.png", precio: 400},
    {nombre: "Chocobreak", categoria: "Dulceria", imagen:"IMAGENES/chocobreak.png", precio: 400} ,
    {nombre: "Trident x3", categoria: "Dulceria", imagen:"IMAGENES/trinden x3.png", precio: 1200},
    {nombre: "Trident Barra", categoria: "Dulceria", imagen:"IMAGENES/trindent barra.png", precio:2200 },
    {nombre: "Halls Unidad", categoria: "Dulceria", imagen:"IMAGENES/halls.png", precio:300 },
    {nombre: "Chicle Xtime", categoria: "Dulceria", imagen:"IMAGENES/Xtime.png", precio:300 },
    {nombre: "Halls en Barra", categoria: "Dulceria", imagen:"IMAGENES/halls barra.png", precio: 2300 },
    {nombre: "Mentas Chao", categoria: "Dulceria", imagen:"IMAGENES/mentas_chao.webp", precio: 200},
    {nombre: "Lokillo", categoria: "Dulceria", imagen:"IMAGENES/lokiño.png", precio: 200},
    {nombre: "Moritas", categoria: "Dulceria", imagen:"IMAGENES/MORITAS.png", precio: 200},
    {nombre: "Chocolores", categoria: "Dulceria", imagen:"IMAGENES/choco colores.png", precio:2200 },
    {nombre: "Sparkies Grande", categoria: "Dulceria", imagen:"IMAGENES/sparkies.png", precio: 2200},
    {nombre: "Jet Pequeña", categoria: "Dulceria", imagen:"IMAGENES/jet.png", precio:1600 },
    {nombre: "Burbujas", categoria: "Dulceria", imagen:"IMAGENES/burbuja.png", precio: 1600},
    {nombre: "Jumbo Mani", categoria: "Dulceria", imagen:"IMAGENES/jumbo mani.png", precio: 4000},
    {nombre: "Festival", categoria: "Dulceria", imagen:"IMAGENES/festival.png", precio:1700 },
    {nombre: "Minichips", categoria: "Dulceria", imagen:"IMAGENES/minichips.png", precio: 1700},
    {nombre: "Club social", categoria: "Dulceria", imagen:"IMAGENES/clubsocial.png", precio: 100 },
    {nombre: "Tosh", categoria: "Dulceria", imagen:"IMAGENES/tosh.png", precio: 1400},
    {nombre: "Oreo", categoria: "Dulceria", imagen:"IMAGENES/oreo x4.png", precio: 1400},
    {nombre: "Saltinas", categoria: "Dulceria", imagen:"IMAGENES/saltinas.png", precio:1400 },
    {nombre: "Dulces", categoria: "Dulceria", imagen:"IMAGENES/dulces.jpg", precio: 100},
    {nombre: "Galletas Chokis", categoria: "Dulceria", imagen:"IMAGENES/chokis.png", precio:2000 },
    {nombre: "Galletas Quaker", categoria: "Dulceria", imagen:"IMAGENES/quaker.png", precio: 2000},
    {nombre: "Galletas Oreo", categoria: "Dulceria", imagen:"IMAGENES/oreo x6.png", precio: 2000},
    {nombre: "Mentas Chao tubo", categoria: "Dulceria", imagen:"IMAGENES/MENTAS_CHAO_TUBO.png", precio: 1300},
    {nombre: "Mentas Chao Linea", categoria: "Dulceria", imagen:"IMAGENES/MENTAS_CHAO_LINEA.png", precio: 800},
    {nombre: "Moritas Paquete", categoria: "Dulceria", imagen:"IMAGENES/MORITAS_PAQUETE.png", precio: 2000},
    {nombre: "Merengon ", categoria: "Dulceria", imagen:"IMAGENES/MERENGON.png", precio:300 },

]