const productos=[
    /*-----------------------------COMIDAS-----------------------*/
    { nombre: "Empanada", categoria: "Comida", imagen:"IMAGENES/EMPANADA.png", precio: 2.800 },
    { nombre: "Arepa de Queso", categoria: "Comida ", magen:"IMAGENES/AREPA QUESO.png", precio: 2.700 },
    { nombre: "Papa Rellena", categoria: "Comida", imagen:"IMAGENES/PAPA RELLENA.png", precio: 3.600},
    { nombre: "Areburguer", categoria: "Comida", imagen:"IMAGENES/AREBURGER.png", precio: 6.300 },
    { nombre: "Hamburguesa", categoria: "Comida", imagen:"IMAGENES/HAMBURGUESA.png", precio: 7.000 },
    { nombre: "Pizza", categoria: "Comida", imagen:"MAGENES/PIZZA.png", precio: 4.600 },
    { nombre: "Sandwich", categoria: "Comida", imagen:"IMAGENES/SANDWICH.png", precio: 3.500 },
    { nombre: "Pastel de Pollo", categoria: "Comida", imagen:"IMAGENES/PASTEL DE POLLO.png", precio: 3.400 },
    { nombre: "Perros", categoria: "Comida", imagen:"IMAGENES/PERRO.png", precio: 5.500 },
    { nombre: "Pastel de Yuca", categoria: "Comida", imagen:"IMAGENES/Pastel de Yuca.png", precio: 3.500 },
    { nombre: "Churros", categoria: "Comida", imagen:"IMAGENES/CHURRO.png", precio: 2.500 },
    { nombre: "Burritos", categoria: "Comida ", imagen:"IMAGENES/BURRITO.png", precio: 6.200 },
    { nombre: "Arepa de Huevo", categoria: "Comida", imagen:"IMAGENES/AREPA DE HUEVO.png", precio: 3.700 },
    { nombre: "Arepa de Jamon y Queso", categoria: "Comida", imagen:"IMAGENES/AREPA JAMÓN Y QUESO.png", precio: 2.700 },
    { nombre: "Sandwich Tajado de Jamon y Queso", categoria: "Comida", imagen:"IMAGENES/SANDWICH JAMÓN Y QUESO.png", precio: 2.000 },
    { nombre: "Sandwich de Pollo", categoria: "Comida", imagen:"IMAGENES/SANDWICH POLLO.png", precio: 6.000 },
    { nombre: "Arepa Blanca", categoria: "Comida", imagen:"IMAGENES/AREPA_SIN_SAL.png", precio: 600},
    {nombre: "Changua", categoria: "Comida", imagen:"", precio:7.500 },
    /* -------------------- BEBIDAS-------------------------------*/
    { nombre: "Hit de vidrio 250", categoria: "Bebidas", imagen:"", precio: 2.300,},
    { nombre: "Postobon Retornable 1.25", categoria: "Bebidas ", imagen:"", precio: 6.000 },
    { nombre: "Amper", categoria: "Bebidas ", imagen:"", precio: 3.700 },
    { nombre: "Red Bull", categoria: "Bebidas ", imagen:"", precio: 8.000 },
    { nombre: "Coca Cola 350ml de Vidrio", categoria: "Bebidas ", imagen:"", precio: 2.700},
    { nombre: "Coca Cola 1.5ml ", categoria: "Bebidas ", imagen:"", precio: 7.000},
    { nombre: "Coca Cola 500ml ", categoria: "Bebidas ", imagen:"", precio: 3.500 },
    { nombre: "Coca Cola Mini", categoria: "Bebidas ", imagen:"", precio: 2.200 },
    { nombre: "Coca Cola Mini de vidrio", categoria: "Bebidas ", imagen:"", precio: 1.800 },
    { nombre: "Natu Mini", categoria: "Bebidas ", imagen:"", precio: 1.700 },
    { nombre: "Natu 400ml", categoria: "Bebidas ", imagen:"", precio: 3.000 },
    { nombre: "Natu de Vidrio", categoria: "Bebidas ", imagen:"", precio: 2.400 },
    { nombre: "Hit en caja", categoria: "Bebidas ", imagen:"", precio: 1.800 },
    { nombre: "Hit 500 ml", categoria: "Bebidas ", imagen:"", precio: 3.200 },
    { nombre: "Aloe", categoria: "Bebidas ", imagen:"", precio: 2.700 },
    { nombre: "speed", categoria: "Bebidas ", imagen:"", precio: 2.000 },
    { nombre: "Bretaña", categoria: "Bebidas ", imagen:"", precio: 3.000 },
    { nombre: "Squash", categoria: "Bebidas ", imagen:"", precio: 3.000 },
    { nombre: "Agua de Litro", categoria: "Bebidas ", imagen:"", precio: 2.800 },
    { nombre: "Agua 300ml", categoria: "Bebidas ", imagen:"", precio: 1.000 },
    { nombre: "Agua con Gas pequeña", categoria: "Bebidas ", imagen:"", precio: 1.000 },
    { nombre: "Aguas 600", categoria: "Bebidas ", imagen:"", precio: 2.2000 },
    { nombre: "Agua con Gas Grande", categoria: "Bebidas ", imagen:"", precio: 2.300 },
    { nombre: "Agua H2O pequeña", categoria: "Bebidas ", imagen:"", precio: 1.700 },
    { nombre: "Agua H2O", categoria: "Bebidas ", imagen:"", precio: 3.200 },
    { nombre: "Mister Tea", categoria: "Bebidas ", imagen:"", precio: 3.000 },
    { nombre: "Te Hatsu", categoria: "Bebidas ", imagen:"", precio: 5.200 },
    { nombre: "Gaseosa Postobon Vidrio", categoria: "Bebidas ", imagen:"", precio: 1.700 },
    { nombre: "Acua", categoria: "Bebidas ", imagen:"", precio: 1.900 },
    { nombre: "Tuti-Fruti", categoria: "Bebidas ", imagen:"", precio: 1.900 },
    { nombre: "Gatorade sin Azucar", categoria: "Bebidas ", imagen:"", precio: 4.000},
    { nombre: "Gatorade", categoria: "Bebidas ", imagen:"", precio: 4.000 },
    { nombre: "Vaso de Gaseosa", categoria: "Bebidas ", imagen:"", precio: 1.000 },
    {nombre: "Electrolit", categoria: "Bebidas", imagen:"", precio:8.800 },
    /*------------------------------COMBOS---------------------------*/
    { nombre: "Combo de Sandwich", categoria: "Combos ", imagen:"", precio: 4.400},
    { nombre: "Combo Pastel de Pollo", categoria: "Combos ", imagen:"", precio: 4.200},
    { nombre: "Combo Hamburguesa", categoria: "Combos ", imagen:"", precio: 7.800},
    { nombre: "Combo Areburguer", categoria: "Combos ", imagen:"", precio: 7.000},
    { nombre: "Combo Perro", categoria: "Combos ", imagen:"", precio: 6.300},
    { nombre: "Salchichon", categoria: "Combos ", imagen:"", precio: 300},
    { nombre: "Pan solo", categoria: "Combos ", imagen:"", precio: 1.200},
    { nombre: "Huevo Cocido", categoria: "Combos ", imagen:"", precio: 1.400},
    { nombre: "Tamales", categoria: "Combos ", imagen:"", precio: 7.600},
    { nombre: "Huevo Rancheros", categoria: "Combos ", imagen:"", precio: 5.200},
    { nombre: "Huevos al Gusto", categoria: "Combos ", imagen:"", precio: 4.700},
    { nombre: "Huevpos Pericos con Salchicha", categoria: "Combos ", imagen:"", precio: 5.700},
    {nombre: "Adicion Salchicha Ranchera", categoria: "Combos", imagen:"", precio: 1.700},
    {nombre: "Lasaña", categoria: "Dulceria", imagen:"", precio:14.000 },
    /*----------------------------------PAQUETES------------------------------ */
    { nombre: "Detodito", categoria: "Paquetes ", imagen:"", precio: 3.200},
    { nombre: "Papas", categoria: "Paquetes ", imagen:"", precio: 2.600},
    { nombre: "Platanos", categoria: "Paquetes ", imagen:"", precio: 2.600},
    { nombre: "Doritos", categoria: "Paquetes ", imagen:"", precio: 2.800},
    { nombre: "Chitos", categoria: "Paquetes ", imagen:"", precio: 2.200},
    { nombre: "Choclitos", categoria: "Paquetes ", imagen:"", precio: 2.200},
    { nombre: "Trocipollo Pequeño", categoria: "Paquetes ", imagen:"", precio: 1.800},
    { nombre: "Trocipollos Grande", categoria: "Paquetes ", imagen:"", precio: 3.000},
    { nombre: "Cheese tris", categoria: "Paquetes ", imagen:"", precio: 2.200},
    { nombre: "Tostacos", categoria: "Paquetes ", imagen:"", precio: 2.200},
    { nombre: "Doritos Dinamita", categoria: "Paquetes ", imagen:"", precio: 3.300},
    { nombre: "Mani con sal", categoria: "Paquetes ", imagen:"", precio: 2.000},
    { nombre: "Mani con pasas", categoria: "Paquetes ", imagen:"", precio: 2.000},
    { nombre: "ManiMoto", categoria: "Paquetes ", imagen:"", precio: 2.000},
    { nombre: "Chokis Bolitas", categoria: "Paquetes ", imagen:"", precio: 2.000},
    { nombre: "Gomitas paquete", categoria: "Paquetes ", imagen:"", precio: 2.700},
    { nombre: "Herpos", categoria: "Paquetes ", imagen:"", precio: 800},
    { nombre: "Chocoramo", categoria: "Paquetes ", imagen:"", precio: 2.800},
    { nombre: "Gala", categoria: "Paquetes ", imagen:"", precio: 2.500},
    { nombre: "Gansito", categoria: "Paquetes ", imagen:"", precio: 1.900},
    { nombre: "Chocoramo Barrita", categoria: "Paquetes ", imagen:"", precio: 2.000},
    {nombre: "Achiras", categoria: "Paquetes ", imagen:"", precio: 4.700},
    {nombre: "Galletas Cocosete", categoria: "Paquetes", imagen:"", precio:2.200 },
    {nombre: "Cheese tris Grandes", categoria: "Dulceria", imagen:"", precio:4.500 },
    /*-------------------------------HELADOS---------------------------------------------- */
    {nombre: "Bonice", categoria: "Helado ", imagen:"", precio: 1.600},
    {nombre: "Bocato", categoria: "Helado ", imagen:"", precio: 7.000},
    {nombre: "Chococono", categoria: "Helado ", imagen:"", precio: 3.500},
    {nombre: "Artesanales", categoria: "Helado ", imagen:"", precio: 3.600},
    {nombre: "Minions ", categoria: "Helado ", imagen:"", precio: 2.500},
    {nombre: "Aloha Mix", categoria: "Helado ", imagen:"", precio: 3.200},
    {nombre: "Aloha Agua", categoria: "Helado ", imagen:"", precio: 2.500},
    {nombre: "Caseros", categoria: "Helado ", imagen:"", precio: 2.900},
    {nombre: "Chocolisto", categoria: "Helado ", imagen:"", precio: 2.400},
    {nombre: "Platillo", categoria: "Helado ", imagen:"", precio: 3.700},
    {nombre: "Chococono Bakano", categoria: "Helado ", imagen:"", precio: 3.900},
    {nombre: "Polet grande", categoria: "Helado ", imagen:"", precio: 6.500},
    {nombre: "Paleta Jet", categoria: "Helado ", imagen:"", precio: 5.000},
    {nombre: "Compota", categoria: "Helado ", imagen:"", precio: 3.000},
    /*--------------------------------GRECA------------------------------------------------- */
    {nombre: "Tinto Pequeño", categoria: "Greca ", imagen:"", precio: 1.100},
    {nombre: "Tinto Grande", categoria: "Greca ", imagen:"", precio: 1.800},
    {nombre: "Agua de Panela", categoria: "Greca", imagen:"", precio: 1.900},
    {nombre: "Aromatica", categoria: "Greca", imagen:"", precio: 1.100},
    {nombre: "Aromatica Grande ", categoria: "Greca", imagen:"", precio: 1.800},
    {nombre: "Chocolate ", categoria: "Greca", imagen:"", precio: 2.700},
    {nombre: "Milo pequeño", categoria: "Greca", imagen:"", precio: 3.100},
    {nombre: "Milo Grande ", categoria: "Greca", imagen:"", precio: 4.600},
    {nombre: "Milo Deslactosado ", categoria: "Greca", imagen:"", precio: 3.900},
    {nombre: "Perico", categoria: "Greca", imagen:"", precio: 1.400},
    {nombre: "Cafe", categoria: "Greca", imagen:"", precio: 2.100},
    {nombre: "Cafe Deslactosado", categoria: "Greca", imagen:"", precio: 2.600,},
    {nombre: "Te chai en Agua", categoria: "Greca", imagen:"", precio: 2.900},
    {nombre: "Te chai en Leche ", categoria: "Greca", imagen:"", precio: 2.900},
    {nombre: "Vaso con Leche", categoria: "Greca", imagen:"", precio: 2.600},
    {nombre: "Arroz con Leche", categoria: "Greca", imagen:"", precio: 3.300},
    /*------------------------------------JUGOS Y FRUTERIA------------------------------------------- */
    {nombre: "Jugos en Leche", categoria: "Jugos y Fruteria", imagen:"", precio:4.600 },
    {nombre: "Batido Verde ", categoria: "Jugos y Fruteria", imagen:"", precio:4.600 },
    {nombre: "Jugo en Agua", categoria: "Jugos y Fruteria", imagen:"", precio:3.200 },
    {nombre: "Gelatina ", categoria: "Jugos y Fruteria", imagen:"", precio:3.000 },
    {nombre: "Yogurt con Granola", categoria: "Jugos y Fruteria", imagen:"", precio:5.200 },
    {nombre: "Vaso de Yogurt 7onz ", categoria: "Jugos y Fruteria", imagen:"", precio:3.000},
    {nombre: "Porcion de Fruta ", categoria: "Jugos y Fruteria", imagen:"", precio:3.000 },
    {nombre: "Bananos ", categoria: "Jugos y Fruteria", imagen:"", precio:1.000 },
    {nombre: "Manzanas  ", categoria: "Jugos y Fruteria", imagen:"", precio: 2.000 },
    {nombre: "Salpicon ", categoria: "Jugos y Fruteria", imagen:"", precio: 2.000 },
    {nombre: "Aguacate ", categoria: "Jugos y Fruteria", imagen:"", precio: 3.000 },
    {nombre: "Merengon ", categoria: "Jugos y Fruteria", imagen:"", precio:300 },
    /*-------------------------------------PASTELERIA---------------------------------------- */
    {nombre: "Galletas de Avena ", categoria: "Pasteleria", imagen:"", precio:1.800 },
    {nombre: "Galletas de Vainilla ", categoria: "Pasteleria", imagen:"", precio:1.000 },
    {nombre: "Galletas de Chocolate ", categoria: "Pasteleria", imagen:"", precio:2.300 },
    {nombre: "Mantecada ", categoria: "Pasteleria", imagen:"", precio:3.000 },
    {nombre: "Torta de Queso  ", categoria: "Pasteleria", imagen:"", precio:3.000 },
    {nombre: "Torta de Naranja ", categoria: "Pasteleria", imagen:"", precio:3.000 },
    {nombre: "Torta de Chocolate ", categoria: "Pasteleria", imagen:"", precio:3.000},
    {nombre: "Brownie", categoria: "Pasteleria", imagen:"", precio:3.800 },
    {nombre: "Torta de Ciruela ", categoria: "Pasteleria", imagen:"", precio:3.800 },
    {nombre: "Milhojas ", categoria: "Pasteleria", imagen:"", precio:3.500 },
    {nombre: "Amapola ", categoria: "Pasteleria", imagen:"", precio:3.500},
    {nombre: "Cocadas", categoria: "Pasteleria", imagen:"", precio:800},
    {nombre: "Flauta ", categoria: "Pasteleria", imagen:"", precio:800},
    {nombre: "Hojaldres de Bocadillo", categoria: "Pasteleria", imagen:"", precio:2.000 },
    {nombre: "Pastel de Carne", categoria: "Pasteleria", imagen:"", precio:3.000 },
    {nombre: "Croisant", categoria: "Pasteleria", imagen:"", precio:2.500},
    /*------------------------------------PRODUCTOS ALPINA---------------------------------------------- */
    {nombre: "Bilack Bolsa", categoria: "Productos Alpina", imagen:"", precio:2.500 },
    {nombre: "Yogurt Alpina Original ", categoria: "Productos Alpina", imagen:"", precio:3.400 },
    {nombre: "Avena Alpina ", categoria: "Productos Alpina", imagen:"", precio:4.200},
    {nombre: "Yox", categoria: "Productos Alpina", imagen:"", precio:3.200},
    {nombre: "Regeneris", categoria: "Productos Alpina", imagen:"", precio:3.900},
    {nombre: "Finesse", categoria: "Productos Alpina", imagen:"", precio: 4.000},
    {nombre: "Bonyurt", categoria: "Productos Alpina", imagen:"", precio: 4.900},
    {nombre: "Alpin en Caja ", categoria: "Productos Alpina", imagen:"", precio:4.000 },
    {nombre: "Yogurt Griego", categoria: "Productos Alpina", imagen:"", precio:6.000},
    {nombre: "Kumis", categoria: "Productos Alpina", imagen:"", precio:3.500},
    {nombre: "Yogo Yogo en Bolsa", categoria: "Productos Alpina", imagen:"", precio:1.900 },
    {nombre: "Arequipe Alpina", categoria: "Productos Alpina", imagen:"", precio: 2.500},
    /*---------------------------------------------DULCERIA--------------------------------------------------- */
    {nombre: "Queso y Quesadilas", categoria: "Dulceria", imagen:"", precio:3.000 },
    {nombre: "Bocadillo Veleño", categoria: "Dulceria", imagen:"", precio:800 },
    {nombre: "Bobbalo", categoria: "Dulceria", imagen:"", precio: 300},
    {nombre: "Bianchi", categoria: "Dulceria", imagen:"", precio:300 },
    {nombre: "Revolcon", categoria: "Dulceria", imagen:"", precio: 300},
    {nombre: "Barrilete", categoria: "Dulceria", imagen:"", precio: 700},
    {nombre: "Frunas", categoria: "Dulceria", imagen:"", precio:700 },
    {nombre: "Bombombum", categoria: "Dulceria", imagen:"", precio: 800},
    {nombre: "Mamut", categoria: "Dulceria", imagen:"", precio: 800},
    {nombre: "Trident Unidad", categoria: "Dulceria", imagen:"", precio: 400},
    {nombre: "Chocobreak", categoria: "Dulceria", imagen:"", precio: 400},
    {nombre: "Trident x3", categoria: "Dulceria", imagen:"", precio: 1.200},
    {nombre: "Trident Barra", categoria: "Dulceria", imagen:"", precio:2.200 },
    {nombre: "Halls Unidad", categoria: "Dulceria", imagen:"", precio:300 },
    {nombre: "Chicle Xtime", categoria: "Dulceria", imagen:"", precio:300 },
    {nombre: "Halls en Barra", categoria: "Dulceria", imagen:"", precio: 2.300 },
    {nombre: "Mentas Chao", categoria: "Dulceria", imagen:"", precio: 200},
    {nombre: "Lokillo", categoria: "Dulceria", imagen:"", precio: 200},
    {nombre: "Moritas", categoria: "Dulceria", imagen:"", precio: 200},
    {nombre: "Chocolores", categoria: "Dulceria", imagen:"", precio:2.200 },
    {nombre: "Sparkies Grande", categoria: "Dulceria", imagen:"", precio: 2.200},
    {nombre: "Jet Pequeña", categoria: "Dulceria", imagen:"", precio:1.600 },
    {nombre: "Burbujas", categoria: "Dulceria", imagen:"", precio: 1.600},
    {nombre: "Jumbo Mani", categoria: "Dulceria", imagen:"", precio: 4.000},
    {nombre: "Festival", categoria: "Dulceria", imagen:"", precio:1.700 },
    {nombre: "Minichips", categoria: "Dulceria", imagen:"", precio: 1.700},
    {nombre: "Club social", categoria: "Dulceria", imagen:"", precio: 1.200 },
    {nombre: "Tosh", categoria: "Dulceria", imagen:"", precio: 1.400},
    {nombre: "Oreo", categoria: "Dulceria", imagen:"", precio: 1.400},
    {nombre: "Saltinas", categoria: "Dulceria", imagen:"", precio:1.400 },
    {nombre: "Dulces", categoria: "Dulceria", imagen:"", precio: 100},
    {nombre: "Galletas Chokis", categoria: "Dulceria", imagen:"", precio:2.000 },
    {nombre: "Galletas Quaker", categoria: "Dulceria", imagen:"", precio: 2.000},
    {nombre: "Galletas Oreo", categoria: "Dulceria", imagen:"", precio: 2.000},
    {nombre: "Mentas Chao tubo", categoria: "Dulceria", imagen:"", precio: 1.300},
    {nombre: "Mentas Chao Linea", categoria: "Dulceria", imagen:"", precio: 800},
    {nombre: "Tajada de Queso", categoria: "Dulceria", imagen:"", precio: 600 },
    {nombre: "Salchichas ", categoria: "Dulceria", imagen:"", precio:4.500 },
    {nombre: "Moritas Paquete", categoria: "Dulceria", imagen:"", precio: 2.000},

]