const productos=[
    /*-----------------------------COMIDAS-----------------------*/
    { nombre: "Empanada", categoria: "Comida", imagen:"IMAGENES/EMPANADA.webp", precio: null },
    { nombre: "Papa Rellena", categoria: "Comida", imagen:"IMAGENES/PAPA RELLENA.webp", precio: null},
    { nombre: "Areburguer", categoria: "Comida", imagen:"IMAGENES/AREBURGER.webp", precio: null },
    { nombre: "Hamburguesa", categoria: "Comida", imagen:"IMAGENES/HAMBURGUESA.webp", precio: null },
    { nombre: "Pizza", categoria: "Comida", imagen:"IMAGENES/PIZZA.webp", precio: null },
    { nombre: "Arepa de Queso", categoria: "Comida ", imagen:"IMAGENES/AREPA_QUESO.webp", precio: null },
    { nombre: "Sandwich", categoria: "Comida", imagen:"IMAGENES/SANDWICH.webp", precio: null },
    { nombre: "Pastel de Pollo", categoria: "Comida", imagen:"IMAGENES/PASTEL DE POLLO.webp", precio: null },
    { nombre: "Perros", categoria: "Comida", imagen:"IMAGENES/PERRO.webp", precio: null },
    { nombre: "Pastel de Yuca", categoria: "Comida", imagen:"IMAGENES/Pastel de Yuca.webp", precio: null },
    { nombre: "Churros", categoria: "Comida", imagen:"IMAGENES/CHURRO.webp", precio: null },
    { nombre: "Burritos", categoria: "Comida ", imagen:"IMAGENES/BURRITO.webp", precio: null },
    { nombre: "Arepa de Huevo", categoria: "Comida", imagen:"IMAGENES/AREPA DE HUEVO.webp", precio: null },
    { nombre: "Arepa de Jamon y Queso", categoria: "Comida", imagen:"IMAGENES/AREPA JAMÓN Y QUESO.webp", precio: null },
    { nombre: "Sandwich Tajado de Jamon y Queso", categoria: "Comida", imagen:"IMAGENES/SANDWICH JAMÓN Y QUESO.webp", precio: null },
    { nombre: "Sandwich de Pollo", categoria: "Comida", imagen:"IMAGENES/SANDWICH POLLO.webp", precio: null },
    { nombre: "Arepa Blanca", categoria: "Comida", imagen:"IMAGENES/AREPA_SIN_SAL.webp", precio: null},
    {nombre: "Changua", categoria: "Comida", imagen:"IMAGENES/CHANGUA.webp", precio:null },
    { nombre: "Salchichon", categoria: "comida", imagen:"IMAGENES/Salchichon.webp", precio: null},
    { nombre: "Pan solo", categoria: "Comida", imagen:"IMAGENES/Pan.webp", precio: null},
    { nombre: "Huevo Cocido", categoria: "Comida", imagen:"IMAGENES/Huevo Cocido.webp", precio: null},
    { nombre: "Tamales", categoria: "Comida", imagen:"IMAGENES/Tamal.webp", precio: null},
    { nombre: "Huevo Rancheros", categoria: "Comida", imagen:"IMAGENES/Huevos con Salchicha.webp", precio: null},
    { nombre: "Huevos al Gusto", categoria: "Comida ", imagen:"IMAGENES/Huevos al Gusto.webp", precio: null},
    { nombre: "Huevpos Pericos con Salchicha", categoria: "Comida", imagen:"IMAGENES/Huevos Pericos con Salchicha.webp", precio: null},
    { nombre: "Adicion Salchicha Ranchera", categoria: "Comida", imagen:"IMAGENES/ADICION_SALCHICHA_RANCHERA.webp", precio: null},
    { nombre: "Lasaña", categoria: "Comida", imagen:"IMAGENES/LASAÑA_.webp", precio:null },
    {nombre: "Pastel de Carne", categoria: "Comida", imagen:"IMAGENES/Pastel de Carne.webp", precio:null },
    {nombre: "Tajada de Queso", categoria: "Comida", imagen:"IMAGENES/QUESO_TAJADO.webp", precio: null },
    {nombre: "Salchichas ", categoria: "Comida", imagen:"IMAGENES/SALCHICHA.webp", precio:null },
    /* -------------------- BEBIDAS-------------------------------*/
    { nombre: "Hit de vidrio 250", categoria: "Bebidas", imagen:"IMAGENES/HIT VIDRIO 250.webp", precio: null,},
    { nombre: "Postobon Retornable 1.25", categoria: "Bebidas ", imagen:"IMAGENES/POSTOBÓN RETORNABLE 1.25.webp", precio: null },
    { nombre: "Amper", categoria: "Bebidas ", imagen:"IMAGENES/AMPER.webp", precio: null },
    { nombre: "Red Bull", categoria: "Bebidas ", imagen:"IMAGENES/REDBULL.webp", precio: null },
    { nombre: "Coca Cola 350ml de Vidrio", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA 350 VIDRIO.webp", precio: null},
    { nombre: "Coca Cola 1.5ml ", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA 1.5.webp", precio: null},
    { nombre: "Coca Cola 500ml ", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA 500 ML.webp", precio: null },
    { nombre: "Coca Cola Mini", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA MINI.webp", precio: null },
    { nombre: "Coca Cola Mini de vidrio", categoria: "Bebidas ", imagen:"IMAGENES/COCA COLA MINI VIDRIO.webp", precio: null },
    { nombre: "Natu Mini", categoria: "Bebidas ", imagen:"IMAGENES/NATU MINI.webp", precio: null },
    { nombre: "Natu 400ml", categoria: "Bebidas ", imagen:"IMAGENES/NATU 400 ML.webp", precio: null },
    { nombre: "Natu de Vidrio", categoria: "Bebidas ", imagen:"IMAGENES/NATU VIDRIO.webp", precio: null },
    { nombre: "Hit en caja", categoria: "Bebidas ", imagen:"IMAGENES/HIT CAJA.webp", precio: null },
    { nombre: "Hit 500 ml", categoria: "Bebidas ", imagen:"IMAGENES/HIT 500 ML.webp", precio: null },
    { nombre: "Aloe", categoria: "Bebidas ", imagen:"IMAGENES/ALOE.webp", precio: null },
    { nombre: "speed", categoria: "Bebidas ", imagen:"IMAGENES/SPEED.webp", precio: null },
    { nombre: "Bretaña", categoria: "Bebidas ", imagen:"IMAGENES/BRETAÑA.webp", precio: null },
    { nombre: "Squash", categoria: "Bebidas ", imagen:"IMAGENES/SQUASH.webp", precio: null },
    { nombre: "Agua de Litro", categoria: "Bebidas ", imagen:"IMAGENES/AGUA LITRO.webp", precio: null },
    { nombre: "Agua 300ml", categoria: "Bebidas ", imagen:"IMAGENES/AGUA_CRISTAL_PEQUEÑA.webp", precio: null },
    { nombre: "Agua con Gas pequeña", categoria: "Bebidas ", imagen:"IMAGENES/AGUA GAS PEQUEÑA.webp", precio: null },
    { nombre: "Aguas 600", categoria: "Bebidas ", imagen:"IMAGENES/AGUA 600 ML.webp", precio: null },
    { nombre: "Agua con Gas Grande", categoria: "Bebidas ", imagen:"IMAGENES/AGUA GAS GRANDE.webp", precio: null },
    { nombre: "Agua H2O pequeña", categoria: "Bebidas ", imagen:"IMAGENES/H2O PEQUEÑA.webp", precio: null },
    { nombre: "Agua H2O", categoria: "Bebidas ", imagen:"IMAGENES/H2O GRANDE.webp", precio: null },
    { nombre: "Mister Tea", categoria: "Bebidas ", imagen:"IMAGENES/MISTER TEA.webp", precio: null },
    { nombre: "Te Hatsu", categoria: "Bebidas ", imagen:"IMAGENES/TE HATSU.webp", precio: null },
    { nombre: "Gaseosa Postobon Vidrio", categoria: "Bebidas ", imagen:"IMAGENES/POSTOBÓN VIDRIO.webp", precio: null },
    { nombre: "Acua", categoria: "Bebidas ", imagen:"IMAGENES/ACQUA.webp", precio: null },
    { nombre: "Tuti-Fruti", categoria: "Bebidas ", imagen:"IMAGENES/TUTIFRUTI.webp", precio: null },
    { nombre: "Gatorade sin Azucar", categoria: "Bebidas ", imagen:"IMAGENES/GATORADE SIN AZÚCAR.webp", precio: null},
    { nombre: "Gatorade", categoria: "Bebidas ", imagen:"IMAGENES/GATORADE.webp", precio: null },
    { nombre: "Gatorlyte", categoria: "Bebidas ", imagen:"IMAGENES/GATORLYTE.webp", precio: null},
    { nombre: "Vaso de Gaseosa", categoria: "Bebidas ", imagen:"IMAGENES/VASO GASEOSA.webp", precio: null },
    { nombre: "Electrolit", categoria: "Bebidas", imagen:"IMAGENES/Elecrolit.webp", precio:null },
    { nombre: "Speed en Lata", categoria: "Bebidas", imagen:"IMAGENES/Espeed en Lata.webp", precio:null },
    { nombre: "Gaseosa Familiar", categoria: "Bebidas", imagen:"IMAGENES/Gaseosa Familiar.webp  ", precio:null },

    /*------------------------------COMBOS---------------------------*/
    { nombre: "Combo de Sandwich", categoria: "Combos ", imagen:"IMAGENES/Combo de Sandwich.webp", precio: null},
    { nombre: "Combo Pastel de Pollo", categoria: "Combos ", imagen:"IMAGENES/PASTEL DE POLLO.webp", precio: null},
    { nombre: "Combo Hamburguesa", categoria: "Combos ", imagen:"IMAGENES/Combo de Hamburguesa.webp", precio: null},
    { nombre: "Combo Areburguer", categoria: "Combos ", imagen:"IMAGENES/Combo Areburguer.webp", precio: null},
    { nombre: "Combo Perro", categoria: "Combos ", imagen:"IMAGENES/combo_perro-removebg-preview.webp", precio: null},

    /*----------------------------------PAQUETES------------------------------ */
    { nombre: "Detodito", categoria: "Paquetes ", imagen:"IMAGENES/detodito.webp", precio: null},
    { nombre: "Papas", categoria: "Paquetes ", imagen:"IMAGENES/papas.webp", precio: null},
    { nombre: "Platanos", categoria: "Paquetes ", imagen:"IMAGENES/platanitos.webp", precio: null},
    { nombre: "Doritos", categoria: "Paquetes ", imagen:"IMAGENES/doritos.webp", precio: null},
    { nombre: "Chitos", categoria: "Paquetes ", imagen:"IMAGENES/cheetos.webp", precio: null},
    { nombre: "Choclitos", categoria: "Paquetes ", imagen:"IMAGENES/choclito.webp", precio: null},
    { nombre: "Trocipollo Pequeño", categoria: "Paquetes ", imagen:"IMAGENES/trocipollo.webp", precio: null},
    { nombre: "Trocipollos Grande", categoria: "Paquetes ", imagen:"IMAGENES/trocippollo grande.webp", precio: null},
    { nombre: "Cheese tris", categoria: "Paquetes ", imagen:"IMAGENES/cheese tres.webp", precio: null},
    { nombre: "Tostacos", categoria: "Paquetes ", imagen:"IMAGENES/tostacos.webp", precio: null},
    { nombre: "Doritos Dinamita", categoria: "Paquetes ", imagen:"IMAGENES/doritos flamin.webp", precio: null},
    { nombre: "Mani con sal", categoria: "Paquetes ", imagen:"IMAGENES/MANI_CON_SAL.webp", precio: null},
    { nombre: "Mani con pasas", categoria: "Paquetes ", imagen:"IMAGENES/mani sal y pasa.webp", precio: null},
    { nombre: "ManiMoto", categoria: "Paquetes ", imagen:"IMAGENES/mani moto.webp", precio: null},
    { nombre: "Chokis Bolitas", categoria: "Paquetes ", imagen:"IMAGENES/CHOKIS_BOLITAS.webp", precio: null},
    { nombre: "Gomitas paquete", categoria: "Paquetes ", imagen:"IMAGENES/gomitas.webp", precio: null},
    { nombre: "Herpos", categoria: "Paquetes ", imagen:"IMAGENES/herpo.webp", precio: null},
    { nombre: "Chocoramo", categoria: "Paquetes ", imagen:"IMAGENES/cohocorramo.webp", precio: null},
    { nombre: "Gala", categoria: "Paquetes ", imagen:"IMAGENES/gala.webp", precio: null},
    { nombre: "Gansito", categoria: "Paquetes ", imagen:"IMAGENES/gansito.webp", precio: null},
    { nombre: "Chocoramo Barrita", categoria: "Paquetes ", imagen:"IMAGENES/CHOCORRAMO_BARRITA.webp", precio: null},
    { nombre: "Achiras", categoria: "Paquetes ", imagen:"IMAGENES/achira.webp", precio: null},
    { nombre: "Galletas Cocosette", categoria: "Paquetes", imagen:"IMAGENES/GALLETAS_COCOSETTE.webp", precio:null },
    { nombre: "Cheese tris Grandes", categoria: "Paquetes", imagen:"IMAGENES/CHEESE_TRIS_GRANDE.webp", precio:null },
    /*-------------------------------HELADOS---------------------------------------------- */
    { nombre: "Bonice", categoria: "Helado ", imagen:"IMAGENES/bonice-removebg-preview.webp", precio: null},
    { nombre: "Bocato", categoria: "Helado ", imagen:"IMAGENES/bocato-removebg-preview.webp", precio: null},
    { nombre: "Chococono", categoria: "Helado ", imagen:"IMAGENES/chococono-removebg-preview.webp", precio: null},
    { nombre: "Artesanales", categoria: "Helado ", imagen:"IMAGENES/helado_artesanal-removebg-preview.webp", precio: null},
    { nombre: "Minions ", categoria: "Helado ", imagen:"IMAGENES/paleta_minions-removebg-preview.webp", precio: null},
    { nombre: "Aloha Mix", categoria: "Helado ", imagen:"IMAGENES/aloha-removebg-preview.webp", precio: null},
    { nombre: "Aloha Agua", categoria: "Helado ", imagen:"IMAGENES/aloha_agua-removebg-preview.webp", precio: null},
    { nombre: "Caseros", categoria: "Helado ", imagen:"IMAGENES/helado_casero-removebg-preview.webp", precio: null},
    { nombre: "Chocolisto", categoria: "Helado ", imagen:"IMAGENES/helado_chocolisto-removebg-preview.webp", precio: null},
    { nombre: "Platillo", categoria: "Helado ", imagen:"IMAGENES/platillo-removebg-preview.webp", precio: null},
    { nombre: "Chococono Bakano", categoria: "Helado ", imagen:"IMAGENES/chococono.webp", precio: null},
    { nombre: "Polet grande", categoria: "Helado ", imagen:"IMAGENES/polet.webp", precio: null},
    { nombre: "Paleta Jet", categoria: "Helado ", imagen:"IMAGENES/paleta_jet.webp", precio: null},
    { nombre: "Compota", categoria: "Helado ", imagen:"IMAGENES/compota.webp", precio: null},
    /*--------------------------------GRECA------------------------------------------------- */
    {nombre: "Tinto Pequeño", categoria: "Greca ", imagen:"IMAGENES/TINTO_PEQUEÑO.webp", precio: null},
    {nombre: "Tinto Grande", categoria: "Greca ", imagen:"IMAGENES/TINTO_GRANDE.webp", precio: null},
    {nombre: "Agua de Panela", categoria: "Greca", imagen:"IMAGENES/Agua de Panela.webp", precio: null},
    {nombre: "Aromatica", categoria: "Greca", imagen:"IMAGENES/Aromatica.webp", precio: null},
    {nombre: "Aromatica Grande ", categoria: "Greca", imagen:"IMAGENES/Aromatica Grande.webp", precio: null},
    {nombre: "Chocolate ", categoria: "Greca", imagen:"IMAGENES/Chocolate.webp", precio: null},
    {nombre: "Milo pequeño", categoria: "Greca", imagen:"IMAGENES/MILO_PEQUEÑO.webp", precio: null},
    {nombre: "Milo Grande ", categoria: "Greca", imagen:"IMAGENES/MILO_GRANDE.webp", precio: null},
    {nombre: "Milo Deslactosado ", categoria: "Greca", imagen:"IMAGENES/Milo Deslactosado.webp", precio: null},
    {nombre: "Perico", categoria: "Greca", imagen:"IMAGENES/PERICO_PEQUEÑO.webp", precio: null},
    {nombre: "Cafe", categoria: "Greca", imagen:"IMAGENES/PERICO_GRANDE.webp", precio: null},
    {nombre: "Cafe Deslactosado", categoria: "Greca", imagen:"IMAGENES/Cafe Deslactosado.webp", precio: null},
    {nombre: "Te chai en Agua", categoria: "Greca", imagen:"IMAGENES/TE_CHAI_AGUA.webp", precio: null},
    {nombre: "Te chai en Leche ", categoria: "Greca", imagen:"IMAGENES/TE_CHAI_LECHE.webp", precio: null},
    {nombre: "Vaso con Leche", categoria: "Greca", imagen:"IMAGENES/Vaso con Leche.webp", precio: null},
    {nombre: "Arroz con Leche", categoria: "Greca", imagen:"IMAGENES/Arroz de Leche.webp", precio: null},
    /*------------------------------------JUGOS Y FRUTERIA------------------------------------------- */
    {nombre: "Jugos en Leche", categoria: "Jugos y Fruteria", imagen:"IMAGENES/JUGOS_LECHE.webp", precio:null },
    {nombre: "Batido Verde ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Batido Verde.webp", precio:null },
    {nombre: "Jugo en Agua", categoria: "Jugos y Fruteria", imagen:"IMAGENES/jugo en agua.webp", precio:null },
    {nombre: "Gelatina ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Gelatina.webp", precio:null },
    {nombre: "Yogurt con Granola", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Yogurt con Granola.webp", precio:null },
    {nombre: "Vaso de Yogurt 7onz ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Vaso de Yogurt.webp", precio:null},
    {nombre: "Porcion de Fruta ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Porcion de Fruta.webp", precio:null },
    {nombre: "Bananos ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Bananos.webp", precio:null },
    {nombre: "Manzanas  ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Manzanas.webp", precio: null },
    {nombre: "Salpicon ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Salpicon.webp", precio: null },
    {nombre: "Aguacate ", categoria: "Jugos y Fruteria", imagen:"IMAGENES/Aguacate.webp", precio: null },

    /*-------------------------------------PASTELERIA---------------------------------------- */
    {nombre: "Galletas de Avena ", categoria: "Pasteleria", imagen:"IMAGENES/Galleta de Avena.png", precio:1800 },
    {nombre: "Galletas de Vainilla ", categoria: "Pasteleria", imagen:"IMAGENES/Galletas de Vainilla.png", precio:1000 },
    {nombre: "Galletas de Chocolate ", categoria: "Pasteleria", imagen:"IMAGENES/Galletas de Chocolate.png", precio:2.00 },
    {nombre: "Mantecada ", categoria: "Pasteleria", imagen:"IMAGENES/Mantecada.png", precio:3000 },
    {nombre: "Torta de Queso  ", categoria: "Pasteleria", imagen:"IMAGENES/Torta de Queso.png", precio:3000 },
    {nombre: "Torta de Naranja ", categoria: "Pasteleria", imagen:"IMAGENES/Torta de Naranja.png", precio:3000 },
    {nombre: "Torta de Chocolate ", categoria: "Pasteleria", imagen:"IMAGENES/TORTA_CHOCOLATE.png", precio:3000},
    {nombre: "Brownie", categoria: "Pasteleria", imagen:"IMAGENES/Brownie.png", precio:3800 },
    {nombre: "Torta de Ciruela ", categoria: "Pasteleria", imagen:"IMAGENES/TORTA_CIRUELA.png", precio:3800 },
    {nombre: "Milhojas ", categoria: "Pasteleria", imagen:"IMAGENES/Milhojas - Amapolas.png", precio:3500 },
    {nombre: "Amapola ", categoria: "Pasteleria", imagen:"", precio:3500},
    {nombre: "Cocadas", categoria: "Pasteleria", imagen:"IMAGENES/Cocadas.png", precio:800},
    {nombre: "Flauta ", categoria: "Pasteleria", imagen:"", precio:800},
    {nombre: "Hojaldres de Bocadillo", categoria: "Pasteleria", imagen:"IMAGENES/Hojaldras de Bocadillo.png", precio:2000 },
    {nombre: "Croisant", categoria: "Pasteleria", imagen:"IMAGENES/CROISSANT.png", precio:2500},
    /*------------------------------------PRODUCTOS ALPINA---------------------------------------------- */
     {nombre: "Bilack Bolsa", categoria: "Productos Alpina", imagen:"IMAGENES/Bilack Bolsa.webp", precio:null },
    {nombre: "Yogurt Alpina Original ", categoria: "Productos Alpina", imagen:"IMAGENES/Yogurt Alpina Original.webp", precio:null },
    {nombre: "Avena Alpina ", categoria: "Productos Alpina", imagen:"IMAGENES/Avena Alpina.webp", precio:null},
    {nombre: "Yox", categoria: "Productos Alpina", imagen:"IMAGENES/Yox.webp", precio:null},
    {nombre: "Regeneris", categoria: "Productos Alpina", imagen:"IMAGENES/Regeneris.webp", precio:null},
    {nombre: "Finesse", categoria: "Productos Alpina", imagen:"IMAGENES/Finesse - Original Deslactosado.webp", precio: null},
    {nombre: "Bonyurt", categoria: "Productos Alpina", imagen:"IMAGENES/Bonyurt.webp", precio: null},
    {nombre: "Alpin en Caja ", categoria: "Productos Alpina", imagen:"IMAGENES/Alpin en Caja.webp", precio:null },
    {nombre: "Yogurt Griego", categoria: "Productos Alpina", imagen:"IMAGENES/YOGURT_GRIEGO.webp", precio:null},
    {nombre: "Kumis", categoria: "Productos Alpina", imagen:"IMAGENES/Kumis.webp", precio:null},
    {nombre: "Yogo Yogo en Bolsa", categoria: "Productos Alpina", imagen:"IMAGENES/Yogo Yogo en Bolsa.webp", precio:null },
    {nombre: "Arequipe Alpina", categoria: "Productos Alpina", imagen:"IMAGENES/Arequipe Alpina.webp", precio: null},
    /*---------------------------------------------DULCERIA--------------------------------------------------- */
     {nombre: "Queso y Quesadilas", categoria: "Dulceria", imagen:"IMAGENES/queso_quesadillas.webp", precio:null },
    {nombre: "Bocadillo Veleño", categoria: "Dulceria", imagen:"IMAGENES/bocadillo_veleño.webp", precio:null },
    {nombre: "Bobbalo", categoria: "Dulceria", imagen:"IMAGENES/bobbaloo.webp", precio: null},
    {nombre: "Bianchi", categoria: "Dulceria", imagen:"IMAGENES/bianchi.webp", precio:null },
    {nombre: "Revolcon", categoria: "Dulceria", imagen:"IMAGENES/revolcon.webp", precio: null},
    {nombre: "Barrilete", categoria: "Dulceria", imagen:"IMAGENES/barrilete.webp", precio: null},
    {nombre: "Frunas", categoria: "Dulceria", imagen:"IMAGENES/frunas.webp", precio:null },
    {nombre: "Bombombum", categoria: "Dulceria", imagen:"IMAGENES/bombom bum.webp", precio: null},
    {nombre: "Mamut", categoria: "Dulceria", imagen:"IMAGENES/mamut.webp", precio: null},
    {nombre: "Trident Unidad", categoria: "Dulceria", imagen:"IMAGENES/trident 1.webp", precio: null},
    {nombre: "Chocobreak", categoria: "Dulceria", imagen:"IMAGENES/chocobreak.webp", precio: null} ,
    {nombre: "Trident x3", categoria: "Dulceria", imagen:"IMAGENES/trinden x3.webp", precio: null},
    {nombre: "Trident Barra", categoria: "Dulceria", imagen:"IMAGENES/trindent barra.webp", precio:null },
    {nombre: "Halls Unidad", categoria: "Dulceria", imagen:"IMAGENES/halls.webp", precio:null },
    {nombre: "Chicle Xtime", categoria: "Dulceria", imagen:"IMAGENES/Xtime.webp", precio:null },
    {nombre: "Halls en Barra", categoria: "Dulceria", imagen:"IMAGENES/halls barra.webp", precio: null },
    {nombre: "Mentas Chao", categoria: "Dulceria", imagen:"IMAGENES/mentas_chao.webp", precio: null},
    {nombre: "Lokillo", categoria: "Dulceria", imagen:"IMAGENES/lokiño.webp", precio: null},
    {nombre: "Moritas", categoria: "Dulceria", imagen:"IMAGENES/MORITAS.webp", precio: null},
    {nombre: "Chocolores", categoria: "Dulceria", imagen:"IMAGENES/choco colores.webp", precio:null },
    {nombre: "Sparkies Grande", categoria: "Dulceria", imagen:"IMAGENES/sparkies.webp", precio: null},
    {nombre: "Jet Pequeña", categoria: "Dulceria", imagen:"IMAGENES/jet.webp", precio:null },
    {nombre: "Burbujas", categoria: "Dulceria", imagen:"IMAGENES/burbuja.webp", precio: null},
    {nombre: "Jumbo Mani", categoria: "Dulceria", imagen:"IMAGENES/jumbo mani.webp", precio: null},
    {nombre: "Festival", categoria: "Dulceria", imagen:"IMAGENES/festival.webp", precio:null },
    {nombre: "Minichips", categoria: "Dulceria", imagen:"IMAGENES/minichips.webp", precio: null},
    {nombre: "Club social", categoria: "Dulceria", imagen:"IMAGENES/clubsocial.webp", precio: null },
    {nombre: "Tosh", categoria: "Dulceria", imagen:"IMAGENES/tosh.webp", precio: null},
    {nombre: "Oreo", categoria: "Dulceria", imagen:"IMAGENES/oreo x4.webp", precio: null},
    {nombre: "Saltinas", categoria: "Dulceria", imagen:"IMAGENES/saltinas.webp", precio:null },
    {nombre: "Dulces", categoria: "Dulceria", imagen:"IMAGENES/dulces.webp", precio: null},
    {nombre: "Galletas Chokis", categoria: "Dulceria", imagen:"IMAGENES/chokis.webp", precio:null },
    {nombre: "Galletas Quaker", categoria: "Dulceria", imagen:"IMAGENES/quaker.webp", precio: null},
    {nombre: "Galletas Oreo", categoria: "Dulceria", imagen:"IMAGENES/oreo x6.webp", precio: null},
    {nombre: "Mentas Chao tubo", categoria: "Dulceria", imagen:"IMAGENES/MENTAS_CHAO_TUBO.webp", precio: null},
    {nombre: "Mentas Chao Linea", categoria: "Dulceria", imagen:"IMAGENES/MENTAS_CHAO_LINEA.webp", precio: null},
    {nombre: "Moritas Paquete", categoria: "Dulceria", imagen:"IMAGENES/MORITAS_PAQUETE.webp", precio: null},
    {nombre: "Merengon ", categoria: "Dulceria", imagen:"IMAGENES/MERENGON.webp", precio:null },

]